DT-HYUNJUN/recipes-share-site

pjt/settings.py, requirements.txt
=> [ADD] taggit

pjt/settings.py, pjt/urls.py, requirements.txt, tailwind.config.js, templates/base.html
- [ADD] tailwind css
- [ADD] django-browser-reload
=> [ADD] tailwind css

recipes/views/__init__.py
=> [ETC] Separate Views for app 'recipes'

recipes/forms.py, recipes/models.py, recipes/views/recipe_review_views.py, recipes/views/recipe_views.py
- `RecipeReviewCreateView`가 `JSON`을 반환하도록 변경
- `RecipeReviewUpdateView` 미완성
=> [UPDATE] views for Recipe Review

pjt/urls.py, recipes/templates/recipes/recipe_detail.html, recipes/urls.py, recipes/views/recipe_review_views.py
=> [UPDATE] RecipeReviewUpdateView

recipes/templates/recipes/recipe_create.html, recipes/templates/recipes/recipe_list.html, static/css/recipes/index.css, templates/base.html, templates/navbar.html
base에 있던 banner를 recipes/index로 이동
=> [UPDATE] banner

recipes/models.py, recipes/views/recipe_views.py
=> [UPDATE] Permission

templates/navbar.html
네브바 메뉴 부분을 가운데로 오게 수정했습니다 (드디어)
=> [FIX] navbar

recipes/forms.py, recipes/templates/recipes/recipe_create.html, recipes/views/recipe_views.py
- 레시피 생성 화면에서 재료 추가 기능 추가
- 등록되지 않은 재료 추가 기능은 아직 없음
=> [UPDATE] Recipe creation

recipes/views/recipe_review_views.py
=> [FIX] RecipeReviewUpdateView

recipes/templates/recipes/recipe_detail.html, recipes/views/recipe_review_views.py, static/css/recipes/index.css, static/js/recipes/carousel.js, static/js/recipes/review.js, templates/index.html, templates/navbar.html
[UPDATE] recipes detail review
=> [UPDATE] recipes detail review

recipes/templates/recipes/recipe_create.html
=> [FIX] Recipe creation

recipes/templates/recipes/recipe_detail.html, static/js/recipes/review.js
recipes detail 댓글 수정 ajax로 비동기 처리 완료
=> [ADD] recipes detail review

recipes/templates/recipes/recipe_list.html, static/css/recipes/recipe-list.css, templates/base.html
recipe-list page를 만들어봤습니다 !
협조해주신 조원 여러분 
그리고 반응형과 여러 도움을 주신 사장님께 감사드리빈다.
=> [ADD] recipe-list page 만들기

recipes/templates/recipes/recipe_detail.html, recipes/views/recipe_review_views.py, static/js/recipes/review.js
=> [UPDATE] RecipeReview create and delete

accounts/models.py, accounts/templates/accounts/change_password.html, accounts/templates/accounts/login.html, accounts/templates/accounts/signup.html, accounts/templates/accounts/update.html, static/js/accounts/change_password.js, static/js/accounts/signup.js, templates/error.html
- 폼이 조건에 맞지 않게 제출된 경우 에러 메시지가 나타나게 함
- 폼 유효성 검사 변경
- 이메일, 닉네임 필드 수정
=> [UPDATE] form validation

accounts/templates/accounts/profile.html, recipes/templates/recipes/fridge.html, static/js/recipes/fridge.js
레시피 냉장고에 재료 추가하는 input을 datalist로 구현
UX부분 수정하는 중
=> [UPDATE] recipes-fridge-input

recipes/templates/recipes/equips.html, static/js/accounts/logout.js, templates/navbar.html
- 네브바에 냉장고를 넣었어요 !
- 로그아웃 모달을 변경중 입니다
=> [UPDATE] navbar

communities/templates/communities/post_detail.html, communities/views/comment_views.py, communities/views/post_views.py
- post detail 좋아요 비동기 수정 
- comment create 시 post detail 페이지가 나오도록 수정 
- post list에서 해당 글 작성한 사람만 글 수정/삭제 가능하도록 수정해야 함
=> [UPDATE] post detail and comment views

communities/templates/communities/comment_create.html, communities/templates/communities/comment_update.html, communities/templates/communities/post_create.html, communities/templates/communities/post_list.html, communities/templates/communities/post_update.html, communities/views/post_views.py, static/js/communities/index.js, templates/navbar.html
=> [ADD] communities index template

recipes/forms.py, recipes/templates/recipes/recipe_create.html, recipes/views/recipe_views.py, static/js/recipes/create.js
- `select2`를 사용한 재료 선택
- 재료 추가, 레시피 등록 버튼 스타일링
- `js` 분리
=> [UPDATE] ingredient

communities/templates/communities/post_detail.html, communities/templates/communities/post_list.html
- 리스트 목록 정렬 , text truncate
- 디테일 페이지 제목 수정( + 추후에 다시 생각해 보기)
- 디테일 프로필 사진 크기 수정
=> [FIX] communities

communities/templates/communities/post_detail.html, communities/templates/communities/post_list.html, static/js/recipes/review.js, templates/navbar.html
=> [UPDATE] communities detail

recipes/templates/recipes/recipe_search_ingredient.html, recipes/templates/recipes/recipe_search_name.html, recipes/views/recipe_views.py
=> [UPDATE] search_sorting

recipes/models.py
=> [ADD] model 'RecipeStep'

recipes/forms.py, recipes/templates/recipes/recipe_create.html, recipes/views/recipe_views.py, static/js/recipes/create.js
=> [UPDATE] RecipeStep

recipes/forms.py, recipes/models.py, recipes/templates/recipes/recipe_create.html, static/js/recipes/create.js
=> [FIX] recipes

recipes/templates/recipes/fridge.html, recipes/views/recipe_views.py
=> [UPDATE] fridge with ingredient

recipes/admin.py, recipes/models.py, recipes/templates/recipes/recipe_detail.html
- `RecipeStep` 어드민에 등록(이제 어드민 페이지 레시피 생성/수정화면에서 단계별 조리법을 추가할 수 있습니다!)
- `RecipeStep`의 `__str__` 메서드 수정
- `recipe_detail` 템플릿에서 레시피 정보가 나타나도록 수정
=> [UPDATE] recipe

accounts/views.py
=> [UPDATE] view

accounts/templates/accounts/comment.html, accounts/templates/accounts/community.html, accounts/templates/accounts/profile.html, accounts/urls.py, communities/templates/communities/post_detail.html
- 팔로우 /팔로잉 모달 프로필 이미지 뜨게 하기 , 모달 중앙으로 옮기기 , 모달 크기 수정
- 프로필 메뉴 조정 ( template 두개로 나눠서 내가 쓴 댓글 , 내가 쓴 글로 나누기 ) 등등
- 커뮤니티 상세페이지 ( 프로필 연결  + 댓글 , 게시글 작성자 전부 )
=> [UPDATE] profile modal/svg

recipes/templates/recipes/fridge.html, static/js/alert.js, static/js/recipes/fridge.js, static/js/recipes/weather.js, templates/base.html, templates/index.html, templates/navbar.html
- 날씨에 따른 레시피 추천을 상단에 세션을 이용해서 한 번만 뜨게끔 설정
=> [UPDATE] recipes weather

recipes/forms.py, recipes/templates/recipes/difficulty.html, recipes/templates/recipes/recipe_update.html, recipes/urls.py, recipes/views/recipe_views.py, static/js/recipes/difficulty.js, static/js/recipes/update.js
- 레시피 수정 기능 추가
- 레시피 수정은 관리자와 해당 레시피의 작성자만 허용
=> [ADD] RecipeUpdate

recipes/forms.py, recipes/templates/recipes/difficulty.html, recipes/templates/recipes/recipe_create.html, recipes/templates/recipes/recipe_update.html, static/js/recipes/create.js, static/js/recipes/update.js
=> [UPDATE] recipe form validation

recipes/templates/recipes/recipe_list.html
페이지네이션이 a태그로 걸려있어서 필터링이 안되던거 수정함~
=> [FIX] list_page_filtering

communities/views/post_views.py, recipes/templates/recipes/recipe_detail.html, recipes/views/recipe_views.py
쿼리 최적화
- `Recipe` 리스트
- `Recipe` 디테일
- `Post` 리스트
- `Post` 디테일
=> [OPTIMIZE] queries

accounts/forms.py, accounts/templates/accounts/signup.html
=> [UPDATE] feature/birthday_form

recipes/admin.py, recipes/forms.py, recipes/models.py, recipes/templates/recipes/recipe_create.html, recipes/templates/recipes/recipe_detail.html, recipes/templates/recipes/recipe_update.html, recipes/views/recipe_views.py
=> [UPDATE] Equip

recipes/templates/recipes/fridge.html, recipes/templates/recipes/recipe_detail.html, recipes/templates/recipes/recipe_list.html, recipes/templates/recipes/recipe_search_ingredient.html, recipes/templates/recipes/recipe_search_name.html, recipes/views/recipe_views.py, static/img/gift.svg, static/js/alert.js, templates/base.html, templates/controller.html, templates/index.html, templates/navbar.html
=> [UPDATE] recipes fridge

accounts/admin.py, communities/admin.py, communities/models.py, templates/tabular_paginated.html
=> [UPDATE] admin

.config/uwsgi/pjt.ini
=> [ADD] pjt.ini

.config/uwsgi/pjt.ini, .config/uwsgi/uwsgi.service
=> [ADD] nginx configuration update

.config/nginx/pjt.conf
=> [ADD] pjt.conf

.config/uwsgi/pjt.ini
=> [UPDATE] nginx pjt.ini

pjt/settings.py
- setting.py 수정
```python
STATIC_ROOT = BASE_DIR / 'static/'
STATICFILES_DIRS = []
```
=> [ADD] STATIC_ROOT

.config/nginx/pjt.conf
=> [UPDATE] nginx/pjt.conf

.config/nginx/pjt.conf, pjt/settings.py
=> [ADD] domain

pjt/settings.py, recipes/templates/recipes/recipe_list.html
=> [UPDATE] index

accounts/models.py, accounts/templates/accounts/bookmark.html, accounts/templates/accounts/comment.html, accounts/templates/accounts/community.html, accounts/templates/accounts/profile.html, recipes/templates/recipes/recipe_list.html, static/css/recipes/index.css, static/js/recipes/carousel.js
=> [UPDATE] accounts profile

recipes/views/recipe_views.py
=> [FIX] Equip

communities/templates/communities/post_create.html, communities/templates/communities/post_list.html, communities/templates/communities/post_update.html, recipes/templates/recipes/equip.html, recipes/templates/recipes/fridge.html, recipes/templates/recipes/recipe_detail.html, recipes/templates/recipes/recipe_list.html, recipes/templates/recipes/recipe_search.html, recipes/templates/recipes/recipe_search_ingredient.html, recipes/templates/recipes/recipe_search_name.html, static/css/recipes/fridge.css, templates/navbar.html
=> [UPDATE] recipes

recipes/views/recipe_views.py
=> [HOTFIX] Equip

accounts/forms.py, accounts/templates/accounts/update.html, accounts/views.py, recipes/templates/recipes/equip.html, recipes/templates/recipes/recipe_list.html
equip페이지 sorting 추가
filtering 수정
account_update 생일추가
=> [UPDATE] filtering

recipes/templates/recipes/recipe_list.html, recipes/views/recipe_views.py
=> [UPDATE] sorting

accounts/templates/accounts/profile.html, communities/templates/communities/post_detail.html, communities/templates/communities/post_list.html, recipes/templates/recipes/equip.html, recipes/templates/recipes/fridge.html, recipes/templates/recipes/recipe_list.html, static/css/recipes/fridge.css, templates/index.html, templates/navbar.html
=> [UPADTE] recipes

recipes/templates/recipes/recipe_list.html
=> [UPDATE] recipes sorting

accounts/templates/accounts/signup.html
=> [UPDATE] sign up

recipes/templates/recipes/recipe_search_ingredient.html, recipes/templates/recipes/recipe_search_name.html
=> [FIX] list

recipes/views/recipe_views.py
=> [UPDATE] list_views

recipes/templates/recipes/difficulty.html
=> [FIX] difficulty widget

communities/templates/communities/post_detail.html, communities/views/post_views.py, recipes/templates/recipes/recipe_create.html, recipes/templates/recipes/recipe_detail.html, recipes/templates/recipes/recipe_update.html, static/css/recipes/index.css, static/js/communities/review.js, static/js/recipes/carousel.js, static/js/recipes/review.js, static/js/recipes/update.js, templates/base.html, templates/index.html
=> [UPDATE] communities

accounts/templates/accounts/bookmark.html, recipes/templates/recipes/equip.html, recipes/templates/recipes/fridge.html, recipes/templates/recipes/recipe_search.html, recipes/templates/recipes/recipe_search_ingredient.html, recipes/templates/recipes/recipe_search_name.html, templates/index.html
=> [FIX] index

communities/views/post_views.py
=> [OPTIMIZE] query for post detail

communities/templates/communities/post_update.html, static/js/communities/update.js, templates/index.html
- `post` 수정 폼 수정
- `index` 템플릿 오타 수정
=> [FIX] post update form and typo

accounts/models.py
=> [FIX] profile image
